### PR TITLE
Populate component and action info when used with Phoenix

### PR DESCRIPTION
**Pull request by minhajuddin**
Completes #72

### CODE REVIEW

**Comment by minhajuddin** [comment]
One of the tests is failing because of the upgraded plug dependency in our mix lock file. We need to sort out #110 before we address this.

**Comment by minhajuddin** [comment]
@joshuap this is ready to be merged after a review.

**Comment by minhajuddin** [comment]
Sorry about the changelog entry. Added now. Also rebased and squished all the commits

**Comment by joshuap** [comment]
Thanks!

**Pull request merged**
