### PR TITLE
Respect URL filtering in cgi_data

### LINKED ISSUE #102: Setting filter_disable_url does not filter url info from the Environment
The Environment section of the error has 3 url related keys `ORIGINAL_FULLPATH`, `QUERY_STRING` and `PATH_INFO`. These keys should be filtered out when `filter_disable_url` is set. As of now, this info is being sent even when `filter_disable_url` is set.

### PR DESCRIPTION
**Pull request by sorentwo**
This adds filtering for URL related fields when `filter_disable_url` is configured. Along the way it also refactors the structure of the filter modules and adds a helper to simply testing configuration settings.

Closes #102

### CODE REVIEW

**Comment by joshuap** [comment]
This will need to be rebased before we can cleanly merge it.

**Comment by sorentwo** [comment]
@joshuap This has been rebased, no more conflicts 👍

**Comment by sorentwo** [comment]
@minhajuddin Sorry about the restructuring, I got a bit overzealous there.

**Comment by joshuap** [comment]
Thanks @sorentwo! 💯

**Pull request merged**
