### PR TITLE
Honeybadger test mix task

### PR DESCRIPTION
**Pull request by minhajuddin**
Adds the ability to simulate an error using a mix task. Completes #36

### CODE REVIEW

**Comment by joshuap** [comment]
@minhajuddin will this report a live error in the development environment by default, or do you need to add the `exclude_envs` config first? If the latter, is it possible to make this task always report a live error?

**Comment by minhajuddin** [comment]
@joshuap Good point about the `excluded_envs`. I have added some code which will mute them before running the task.

**Comment by joshuap** [comment]
Looks good, thanks! One last thing, can you add a changelog entry? Feel free to squash ans merge, the.

**Comment by minhajuddin** [comment]
Added changelog entry and squashed the commits.

**Pull request merged**
