### PR TITLE
Add runtime config support for api_key

### PR DESCRIPTION
**Pull request by aditya7iyengar**
This would allow us to run the same builds on different machines without having to rebuild with a set of configs

### CODE REVIEW

**Comment by mwoods79** [comment]
@aditya7iyengar Wouldn't this do the same thing?

```elixir
# config.exs
config :honeybadger,
  api_key: System.get_env("HONEYBADGER_API_KEY")
```

**Comment by aditya7iyengar** [comment]
@mwoods79 It would, but only if we are creating a build with that config set up. Many companies build an application on a machine and deploy it to separate machines which could have different env variables. So, in this way they can bypass setting up configs at build-time.

Here's how phoenix does it:
https://github.com/phoenixframework/phoenix/blob/master/lib/phoenix/endpoint.ex#L157

**Comment by aditya7iyengar** [comment]
bump @mwoods79

**Comment by aditya7iyengar** [comment]
@mwoods79 Any updates on this one?

**Comment by mwoods79** [comment]
@aditya7iyengar we are currently rethinking the way we initialize and store configuration data. Once we have a better solution (or even decide to keep the current one) then we can explore runtime config keys. Sorry you've been waiting so long for this feature, hopefully it won't be too much longer.

**Pull request closed without merging**
